### ISSUE TITLE
Make plugin compatible with python3

### ISSUE THREAD

**Issue by Napsty** [Napsty/check_esxi_hardware#13]
On Ubuntu 14.04 LTS with python 3.4 the following error is thrown:

```
  File "./check_esxi_hardware.py3", line 440
    print "%s %s" % (time.strftime("%Y%m%d %H:%M:%S"), message)
            ^
SyntaxError: invalid syntax
```

**Comment by Napsty** [comment]
As check_esxi_hardware heavily relies on pywbem and pywbem currently ONLY runs with python 2.7, this is closed as wontfix. I know the pywbem team works on making the module working with Python 3, too (https://github.com/deejross/python3-pywbem) but as long as Python 3 is not officially working, it doesn't make sense yet to rewrite the plugin.

**Comment by sbraz** [comment]
It looks like pywebm now supports Python 3 :) I guess you could re-open this.

**Comment by Napsty** [comment]
Yep! You're right. Your wish is granted. Merry Xmas :)

**Comment by Napsty** [comment]
Some hints to myself:
http://stackoverflow.com/questions/12519554/python3-invalid-syntax 
http://stackoverflow.com/questions/26938799/printing-variables-in-python-3-4
http://www.python-course.eu/python3_formatted_output.php

**Comment by sbraz** [comment]
Works with both Pythons but you need to add `from __future__ import print_function`, otherwise calls to print with more than one argument will display a tuple:
```
$ python2 ./check_esxi_hardware.py …
('20181001 11:31:37', 'Found pywbem version 0.7.0')

$ python3 -c "print(1, 2)"
1 2

$ python2 -c "print(1, 2)"
(1, 2)

$ python2 -c "from __future__ import print_function; print(1, 2)"                                                                                                                          
1 2
```

**Comment by Napsty** [comment]
Thanks, good hint. Added in commit https://github.com/Napsty/check_esxi_hardware/pull/30/commits/6aebd1a4bb7083519a7e83703e9854514189f33d.

**Comment by Napsty** [comment]
python3, here we come! Closing this :)
