### ISSUE TITLE
Plugin hangs at  Check classe OMC_PowerSupply (VMware 6.0 U2)

### ISSUE THREAD

**Issue by MarcusCaepio** [Napsty/check_esxi_hardware#19]
Hi Claudio,
first of all, thanks for this great plugin. We use it to check a lot of Dell esx hosts.
Unfortunately since 2 days we have a problem. We updated the VMware Version to VMware 6.0 U2 and now get a Unknown State because we run in a timeout. 
I checked on CLI in verbose mode and notificed that the Plugin always hangs at one specific point:
20161229 23:34:08 Check classe OMC_Fan
20161229 23:34:08   Element Name = FAN 5 RPM
20161229 23:34:08     Element Op Status = 2
20161229 23:34:08   Element Name = FAN 4 RPM
20161229 23:34:08     Element Op Status = 2
20161229 23:34:08   Element Name = FAN 3 RPM
20161229 23:34:08     Element Op Status = 2
20161229 23:34:08   Element Name = FAN 2 RPM
20161229 23:34:08     Element Op Status = 2
20161229 23:34:08   Element Name = FAN 1 RPM
20161229 23:34:08     Element Op Status = 2
20161229 23:34:08 Check classe OMC_PowerSupply

It stays at PowerSupply forever. On older vmware versions, the plugin still runs smooth. 
Could you help me to fix this?
pywbem version 0.7.0 and python 2.7.5 is installed.
OS is Ubuntu 14.04 

Thanks in advanced and a happy new year!

Regards,

Marcus

**Comment by MarcusCaepio** [comment]
Further Information:
Plugin works without problems on Version 6.0.0 Build 4510822
Plugin works not on Version 6.0.0 Build 4600944

**Comment by Napsty** [comment]
Hello 

I see you posted this already in https://monitoring-portal.org/index.php?thread/39393-check-esxi-hardware-timeout-seit-version-6-0-0-build-4600944/&postID=242205#post242205 

Please follow up in there. Github issues is supposed to report an issue with the program/plugin itself. But it works on that particular VMware ESXi version as I responded in the forum.
