### ISSUE TITLE
ssl error

### ISSUE THREAD

**Issue by fmontaldo** [Napsty/check_esxi_hardware#25]
Hi 

when I check the command it show me the following error.

./check_esxi_hardware.py -H IP –user=root –pass=xxxxxxxx
UNKNOWN: (0, ‘Socket error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)’)

I think it is an error with the CIM provider.

**Comment by Napsty** [comment]
If possible, please update your pywbem version. This error appeared on certain manually patched 0.7 versions of pywbem. See FAQ at https://www.claudiokuenzler.com/blog/308/check-esxi-hardware-faq-frequently-asked-questions .
