### ISSUE TITLE
Problems with LSI CIMs and ESXi 6.7?

### ISSUE THREAD

**Issue by MarcusCaepio** [Napsty/check_esxi_hardware#31]
Hi Claudio,
this is not an issue with the plugin. But as you have/had many contact with VMware, maybe you know this problem too (and maybe know a solution too?). As you know, I use your plugin to check our ESX hw. Especially the status of the RAID is very interesting for us. We are using LSI/Megaraid RAID Controller and in the past, after installing the CIMs on the ESXi server, we got the RAID status both in VMware and your plugin. Now, with ESXi 6.7 it seems, that the CIMs are not working anymore.
We tried CIMs of https://docs.broadcom.com/docs/VMW-ESX-6.5.0-lsiprovider-500.04.V0.71-0004-9942010.zip
and http://www.58support.nec.co.jp/global/download/042581-G02/VMW-ESX-6.0.0-lsiprovider-500.04.V0.69-0004-offline_bundle-8676001.zip according to the forum thread at https://communities.vmware.com/thread/587140?start=15&tstart=0.
Have you already stumbled upon this problem?

Cheers,
Marcus

**Comment by Napsty** [comment]
Hello

Please use the FAQ page for such questions: https://www.claudiokuenzler.com/blog/308/check-esxi-hardware-faq-frequently-asked-questions
Github issues are only for plugin/code related issues.

thx.
