### ISSUE TITLE
memory check error

### ISSUE THREAD

**Issue by majed17** [Napsty/check_esxi_hardware#32]
Peace, nagios produces an error:

  CRITICAL : Memory  - Server:  IBM -[985421A2G]- s/n: 1234567 System BIOS: -[Bla189BUS-3.25]- (Date)
while in vsphere: memory used 235382/3933162 which is obviously less than 90%

**Comment by Napsty** [comment]
Please read the FAQ (https://www.claudiokuenzler.com/blog/308/check-esxi-hardware-faq-frequently-asked-questions). The plugin monitor hardware, not software (e.g. cpu load or memory usage).

**Comment by majed17** [comment]
ahh all this time i thought it was nagging about a memory overload, so what is it reporting then? skimmed the link and didn't find such..

**Comment by Napsty** [comment]
Please don't skim it. Read the FAQ (it's not that long). There are multiple answers which potentially solve this particular error you get from the plugin. ;-)
