### ISSUE TITLE
Add memory and cpu

### ISSUE THREAD

**Issue by jdavidsftp** [Napsty/check_esxi_hardware#40]
I am not sure how to code this one but I know we get alerts for memory and CPU, so it would be awesome if we could get perfdata off of that as well. I know there are some other plugins out there that pull this, but it's based off of SNMP and it's just not as reliable and "all-in-one" as this one. Just a thought for this, and hopefully it wouldn't be too hard to pull!

**Comment by Napsty** [comment]
From the FAQ (https://www.claudiokuenzler.com/blog/308/check-esxi-hardware-faq-frequently-asked-questions):

> Q: Can the plugin also monitor other stuff like VMFS disk usage or cpu/memory usage?
> A: No. The plugin makes use of the CIM (Common Infrastructure Model) API. The so-called CIM elements cover hardware only.

**Comment by Napsty** [comment]
Take a look at the awesome plugin check_vmware_esx: https://github.com/BaldMansMojo/check_vmware_esx
