### ISSUE TITLE
UNKNOWN: Authentication Error for a new user

### ISSUE THREAD

**Issue by riahc3** [Napsty/check_esxi_hardware#41]
Hello

I have retested this several times and even gave it the same permissions as root and I get the same error.

I made a new user, currently with the Administrator role, and every time I run the script with that ESXi user I get a UNKNOWN: Authentication Error for said user.

I can logon to the web console using that user and do whatever operation I want.

Why?

**Comment by Napsty** [comment]
From the FAQ (https://www.claudiokuenzler.com/blog/308/check-esxi-hardware-faq-frequently-asked-questions)

> A: There are several answers to that:
> 1. Make sure you are either using the ESXi root user or that you create a user which is member of the root group. See this post for a short description how to do that.
> 2. The password you are using has some special characters like a question mark and you need to quote them.
> 3. The password you are using has a Dollar sign ($) which you need to single-quote.

> Generally, always put quotes around your password as this assures the content is handled as string. 

Does this help?

You cannot use the "Administrator" role from the UI. Unfortunately it's pretty tricky (even more so in the recent vSphere versions) to access the CIM server with a non-root user.
