### ISSUE TITLE
HP Vendor Issues with Network Class check

### ISSUE THREAD

**Issue by madmax01** [Napsty/check_esxi_hardware#43]
Hi,

just as info

i added  'VMware_EthernetPort',   to the CIM Classes to check because it's very helpfully to get alerts once an Network Port getting issues.

ProLiant DL360 G7

the check with -V hp -i vmnic2,vmnic3     > seems this check doesn't work

i had to use  -V unknown -i vmnic2,vmnic3  then i got alerts fro everything which is not vmnic2/vminc3

thx

Max

**Comment by Napsty** [comment]
This seems to be something inside ESXi software (inside the OS), whether or not the vmnic's are enabled or not.

I just tested this on Cisco UCSC-C220 servers:

```
20200217 09:20:54 Check classe VMware_EthernetPort
20200217 09:20:54   Element Name = vmnic0
20200217 09:20:54     Element Op Status = 10
20200217 09:20:54 Global exit set to CRITICAL
20200217 09:20:54   Element Name = vmnic1
20200217 09:20:54     Element Op Status = 10
20200217 09:20:54 Global exit set to CRITICAL
20200217 09:20:54   Element Name = vmnic2
20200217 09:20:54     Element Op Status = 2
20200217 09:20:54   Element Name = vmnic3
20200217 09:20:54     Element Op Status = 10
20200217 09:20:54 Global exit set to CRITICAL
20200217 09:20:54   Element Name = vmnic4
20200217 09:20:54     Element Op Status = 2
20200217 09:20:54   Element Name = vmnic5
20200217 09:20:54     Element Op Status = 2
20200217 09:20:54   Element Name = vmnic6
20200217 09:20:54     Element Op Status = 2
20200217 09:20:54   Element Name = vmnic7
20200217 09:20:54     Element Op Status = 10
20200217 09:20:54 Global exit set to CRITICAL
20200217 09:20:54   Element Name = vmnic8
20200217 09:20:54     Element Op Status = 2
20200217 09:20:54   Element Name = vmnic9
20200217 09:20:54     Element Op Status = 2
```

As you can see some nics return Op Status 2 (= OK), others return Status 10 (= Stopped). 
To me this CIM Class looks more like "OS-side implementation of the physical NICs" - therefore no surprise for such check results.

**Comment by madmax01** [comment]
Cisco works differently then HP. Pretty. sure.  

all i wanted to say is that "HP" Vendor seems not working 100% with the "-V hp"

i normally just use "-V Auto" . but if something not working i miss it. because it's an HP Server i thought it just works.  but isn't.  so i Need to use  "-V unknown"  then it works for this HP Server above.

for me is fine - i know the workaround. i just wanted to bring up Attention. thx

**Comment by Napsty** [comment]
Yes, this will be renamed in one of the next releases to not focus on hardware vendors but rather on the CIM element names. It's confusing right now, I agree.
