### ISSUE TITLE
SSL problems with older ESXi

### ISSUE THREAD

**Issue by xvdessel** [Napsty/check_esxi_hardware#45]
Hi,
I'm running these versions:
CentOS 8, kernel of Apr 9, 2020
nagios 4.4.5 from CentOS 8 epel repo
check_esxi_hardware.py of 20190701 (latest from master branch)
python 3.6 from CentOS 8 AppStream
first tested with python3-pywbem version 0.11.0 which is the default RPM version from CentOS

Working target system: hpe gen9 server with ESXi 6.7.0 Update 3 (Build 15160138)
The command correctly returns the failing points (e.g. power supply)

Failing Target system: Fujitsu Siemens Primergy TX300 S4
ESXi 5.1.0 build 1021289

command is run in the plugins folder.
./check_esxi_hardware.py -H the_server -U xxx -P yyy
fails with an SSL error during the first classe check (OMC_SMASHFirmwareIdentity). Details are below.

After a nice mail answer from Claudio, he pointed me to a likely outdated pywbem.

Hence, the RPM install of pywbem was removed, and a pip3 install was done as indicated in the FAQ. This has installed version 0.17.2 (which is the most recent one, from April 2020).
Test with the working system proved again that all works fine.

The test with the failing system stays the same. The output of the command (with the verbose option) is below:
```
20200601 01:07:47 LCD Status: True
20200601 01:07:47 Connection to https://<my-server-name>
20200601 01:07:47 Found pywbem version 0.17.2
20200601 01:07:47 Check classe OMC_SMASHFirmwareIdentity
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pywbem/_cim_http.py", line 655, in connect
    return self.sock.connect((self.host, self.port))
  File "/usr/lib64/python3.6/ssl.py", line 1065, in connect
    self._real_connect(addr, False)
  File "/usr/lib64/python3.6/ssl.py", line 1056, in _real_connect
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1033, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 645, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:897)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./check_esxi_hardware.py", line 720, in <module>
    instance_list = wbemclient.EnumerateInstances(classe)
  File "/usr/local/lib/python3.6/site-packages/pywbem/_cim_operations.py", line 2494, in EnumerateInstances
    **extra)
  File "/usr/local/lib/python3.6/site-packages/pywbem/_cim_operations.py", line 1763, in _imethodcall
    conn_id=self.conn_id)
  File "/usr/local/lib/python3.6/site-packages/pywbem/_cim_http.py", line 824, in wbem_request
    client.endheaders()
  File "/usr/lib64/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.6/site-packages/pywbem/_cim_http.py", line 483, in send
    self.connect()  # pylint: disable=no-member
  File "/usr/local/lib/python3.6/site-packages/pywbem/_cim_http.py", line 661, in connect
    conn_id=conn_id)
pywbem._exceptions.ConnectionError: SSL error <class 'ssl.SSLError'>: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:897); OpenSSL version: OpenSSL 1.1.1c FIPS  28 May 2019
```

If you need detail command output from within this ESXi, I can provide these.
Thanks to have a look into this.

**Comment by Napsty** [comment]
This happens due to a newer OS and OpenSSL settings which enforces openssl (which is used at the end to establish the https communication with the ESXi server) to use the newest TLS protocol (currently 1.2) and not below.

As the older ESXi server runs with an older TLS version (probably TLSv1.0), you would have to tell the client side to lower the protocol. This is described in https://pywbem.readthedocs.io/en/latest/appendix.html:

> This is an error that is created by the OpenSSL library and handed back up to the SSL module of Python which hands it up to pywbem. The error indicates that OpenSSL and the WBEM server do not agree about which SSL/TLS protocol level to use.

> Pywbem specifies SSL parameters such that the highest SSL/TLS protocol version is used that both the client and server support. Thus, pywbem does not put any additional restrictions on top of OpenSSL.

> Debian buster includes OpenSSL 1.1.1d and increased its security settings to require at least TLS 1.2 (see https://stackoverflow.com/a/53065682/1424462).

> This error means most likely that the WBEM server side does not yet support TLS 1.2 or higher.

> This can be fixed for example by adding TLS 1.2 support to the server side (preferred) or by lowering the minimum TLS level OpenSSL requires on the client side (which lowers security). The latter can be done by changing the MinProtocol parameter in the OpenSSL config file on the client OS (typically /etc/ssl/openssl.cnf on Linux and OS-X, and C:\OpenSSL-Win64\openssl.cnf on Windows). 

I am looking into a way to do this directly in `check_esxi_hardware.py`, without the need of manually fiddling around in the openssl client config. @xvdessel would it be possible to give me access to a ESXi 5.x server?

**Comment by Napsty** [comment]
I found a way how to solve this with the plugin without the need of additional configuration changes. I will add a new parameter for this purpose: `-S` / `--sslproto` which can then be used to manually tell the plugin to lower the openssl clientside protocol. Working on it, expect a PR soon.

**Comment by Napsty** [comment]
Working successfully with the new (future) release, currently in branch `sslproto`:
https://github.com/Napsty/check_esxi_hardware/blob/sslproto/check_esxi_hardware.py

```
# python3 ./check_esxi_hardware.py  -H 192.168.15.18 -U root -P 123456789 
UNKNOWN: SSL error <class 'ssl.SSLError'>: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1056); OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

Using the new `-S` parameter to use a lower SSL protocol (ESXi 5.0 uses TLSv1.0):

```
# python3 ./check_esxi_hardware.py  -H 192.168.15.18 -U root -P 123456789 -S TLSv1.0
OK - Server: No Enclosure VMware Virtual Platform s/n: VMware-56 4d 2d 03 ea d4 41 97-89 af 93 78 33 7d 9e 32 System BIOS: 6.00 2017-05-19
```

Would be great if someone could test this, too.

**Comment by xvdessel** [comment]
Confirmed OK on an 5.1 ESXi which complained initially.

Thanks!
