### ISSUE TITLE
Controller Alarm not reported

### ISSUE THREAD

**Issue by sronline** [Napsty/check_esxi_hardware#52]
Script does not report Controller Alarm:

![grafik](https://user-images.githubusercontent.com/17158346/104751048-246ea600-5755-11eb-87b9-f34221f0dfac.png)

But vSphere Client does:
![grafik](https://user-images.githubusercontent.com/17158346/104750902-fbe6ac00-5754-11eb-87e2-06a5946ec5d3.png)

**Comment by sronline** [comment]
> 20210115 17:15:31 LCD Status: True
20210115 17:15:31 Chassis Intrusion Status: True
20210115 17:15:31 Connection to https://esxi-1
20210115 17:15:31 Found pywbem version 0.11.0
20210115 17:15:31 Check classe OMC_SMASHFirmwareIdentity
20210115 17:15:31   Element Name = System BIOS
20210115 17:15:31     VersionString = P89
20210115 17:15:31 Check classe CIM_Chassis
20210115 17:15:31   Element Name = Chassis
20210115 17:15:31     Manufacturer = HP
20210115 17:15:31     SerialNumber = CZJ705****
20210115 17:15:31     Model = ProLiant DL380 Gen9
20210115 17:15:31     Element Op Status = 0
20210115 17:15:31 Check classe CIM_Card
20210115 17:15:32   Element Name = Motherboard
20210115 17:15:32     Element Op Status = 0
20210115 17:15:32 Check classe CIM_ComputerSystem
20210115 17:15:32   Element Name = ESXI-1.****
20210115 17:15:32   Element Name = Smart Array P440ar RAID Controller : Embedded : HPSA1
20210115 17:15:32 Check classe CIM_NumericSensor
20210115 17:15:32 Check classe CIM_Memory
20210115 17:15:32   Element Name = Proc 1 Level-2 Cache
20210115 17:15:32     Element Op Status = 0
20210115 17:15:32   Element Name = Proc 1 Level-3 Cache
20210115 17:15:32     Element Op Status = 0
20210115 17:15:32   Element Name = Memory
20210115 17:15:32 Check classe CIM_Processor
20210115 17:15:33   Element Name = Proc 1
20210115 17:15:33     Family = 179
20210115 17:15:33     CurrentClockSpeed = 2100MHz
20210115 17:15:33     Element Op Status = 2
20210115 17:15:33 Check classe CIM_RecordLog
20210115 17:15:33 Check classe OMC_DiscreteSensor
20210115 17:15:33 Check classe OMC_Fan
20210115 17:15:33 Check classe OMC_PowerSupply
20210115 17:15:34 Check classe VMware_StorageExtent
20210115 17:15:34   Element Name = Disk 1 on HPSA1 : Port 1I Box 3 Bay 4 : 558GB : Data Disk
20210115 17:15:34   Element Name = Disk 2 on HPSA1 : Port 1I Box 3 Bay 3 : 558GB : Data Disk
20210115 17:15:34   Element Name = Disk 3 on HPSA1 : Port 1I Box 3 Bay 2 : 558GB : Data Disk
20210115 17:15:34   Element Name = Disk 4 on HPSA1 : Port 1I Box 3 Bay 1 : 558GB : Data Disk
20210115 17:15:34   Element Name = Disk 5 on HPSA1 : Port 2I Box 3 Bay 5 : 558GB : Data Disk
20210115 17:15:34   Element Name = Disk 6 on HPSA1 : Port 2I Box 3 Bay 6 : 558GB : Data Disk
20210115 17:15:34   Element Name = Disk 7 on HPSA1 : Port 2I Box 3 Bay 7 : 558GB : Data Disk
20210115 17:15:34   Element Name = Disk 8 on HPSA1 : Port 2I Box 3 Bay 8 : 558GB : Data Disk
20210115 17:15:34 Check classe VMware_Controller
20210115 17:15:34   Element Name = Smart Array P440ar RAID Controller : Embedded : HPSA1
20210115 17:15:34 Check classe VMware_StorageVolume
20210115 17:15:35   Element Name = Logical Volume 1 on HPSA1 : RAID 6 : 1117GB : Disk 1,2,3,4
20210115 17:15:35   Element Name = Logical Volume 2 on HPSA1 : RAID 6 : 1117GB : Disk 5,6,7,8
20210115 17:15:35 Check classe VMware_Battery
20210115 17:15:35 Check classe VMware_SASSATAPort

**Comment by Napsty** [comment]
How exactly did you run check_esxi_hardware? Which parameters?

**Comment by sronline** [comment]
./check_esxi_hardware.py -H HOST -U USER -P PASS -v

**Comment by Napsty** [comment]
As you are using a HP server, can you try with `./check_esxi_hardware.py -H HOST -U USER -P PASS -V hp -v` ?

**Comment by sronline** [comment]
Thank you. It works:

CRITICAL : Smart Array P440ar RAID Controller : Embedded : HPSA1  CRITICAL : Smart Array P440ar RAID Controller : Embedded : HPSA1  - Server:  HP ProLiant DL380 Gen9 s/n: CZJ705**** System BIOS: P89 2017-10-25

**Comment by Napsty** [comment]
Great, thanks for the feedback.
