### ISSUE TITLE
The script doesn't work on Ubuntu 20.04

### ISSUE THREAD

**Issue by tikondrus** [Napsty/check_esxi_hardware#53]
./check_esxi_hardware.py
Traceback (most recent call last):
  File "./check_esxi_hardware.py", line 287, in <module>
    import pywbem
ImportError: No module named pywbem

# apt install python-pywbem
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package python-pywbem is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  sblim-wbemcli

I've installed sblim-wbemcli package but it didn't resolve the issue

**Comment by tikondrus** [comment]
#  pip3 install pywbem
Requirement already satisfied: pywbem in /usr/local/lib/python3.8/dist-packages (1.1.3)
Requirement already satisfied: nocasedict>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from pywbem) (1.0.2)
Requirement already satisfied: ply>=3.10 in /usr/local/lib/python3.8/dist-packages (from pywbem) (3.11)
Requirement already satisfied: requests>=2.20.0 in /usr/lib/python3/dist-packages (from pywbem) (2.22.0)
Requirement already satisfied: mock>=2.0.0; python_version >= "3.6" in /usr/local/lib/python3.8/dist-packages (from pywbem) (4.0.3)
Requirement already satisfied: six>=1.14.0 in /usr/lib/python3/dist-packages (from pywbem) (1.14.0)
Requirement already satisfied: nocaselist>=1.0.3 in /usr/local/lib/python3.8/dist-packages (from pywbem) (1.0.4)
Requirement already satisfied: PyYAML>=5.1; python_version > "3.4" in /usr/lib/python3/dist-packages (from pywbem) (5.3.1)
Requirement already satisfied: yamlloader>=0.5.5 in /usr/local/lib/python3.8/dist-packages (from pywbem) (1.0.0)

**Comment by Napsty** [comment]
Hi @tikondrus 

I just tested this on a Ubuntu 20.04 with an ESXi 7.0 target.
pywbem was installed with pip3 (the deb package does not exist anymore):

```
root@focal:~# pip3 list | grep pywbem
pywbem                 1.1.3         
```

The plugin runs correctly against the ESXi machine:

```
root@focal:~# /usr/lib/nagios/plugins/check_esxi_hardware.py -H esxi -U root -P Secret123. -v
20210408 15:00:48 LCD Status: True
20210408 15:00:48 Chassis Intrusion Status: True
20210408 15:00:48 Connection to https://192.168.15.10
20210408 15:00:48 Found pywbem version 1.1.3
20210408 15:00:48 Check classe OMC_SMASHFirmwareIdentity
20210408 15:00:48   Element Name = System BIOS
20210408 15:00:48     VersionString = VMW71.00V.16722896.B64.2008100651
20210408 15:00:48 Check classe CIM_Chassis
20210408 15:00:48   Element Name = Chassis
20210408 15:00:48     Manufacturer = No Enclosure
20210408 15:00:48     SerialNumber = VMware-56 4d 4b bc 8e 12 44 4f-65 2a 1a 62 7c 09 d3 2c
20210408 15:00:48     Model = VMware7,1
20210408 15:00:48     Element Op Status = 0
20210408 15:00:48 Check classe CIM_Card
20210408 15:00:48   Element Name = Unknown
20210408 15:00:48     Element Op Status = 0
20210408 15:00:48 Check classe CIM_ComputerSystem
20210408 15:00:48   Element Name = localhost
20210408 15:00:48 Check classe CIM_NumericSensor
20210408 15:00:48 Check classe CIM_Memory
20210408 15:00:49   Element Name = Memory
20210408 15:00:49 Check classe CIM_Processor
20210408 15:00:49   Element Name = CPU 0
20210408 15:00:49     Family = 2
20210408 15:00:49     CurrentClockSpeed = 3426MHz
20210408 15:00:49     Element Op Status = 2
20210408 15:00:49   Element Name = CPU 1
20210408 15:00:49     Family = 2
20210408 15:00:49     CurrentClockSpeed = 3426MHz
20210408 15:00:49     Element Op Status = 2
20210408 15:00:49 Check classe CIM_RecordLog
20210408 15:00:49 Check classe OMC_DiscreteSensor
20210408 15:00:49 Check classe OMC_Fan
20210408 15:00:49 Check classe OMC_PowerSupply
20210408 15:00:49 Check classe VMware_StorageExtent
20210408 15:00:50 Check classe VMware_Controller
20210408 15:00:50 Check classe VMware_StorageVolume
20210408 15:00:50 Check classe VMware_Battery
20210408 15:00:50 Check classe VMware_SASSATAPort
OK - Server: No Enclosure VMware7,1 s/n: VMware-56 4d 4b bc 8e 12 44 4f-65 2a 1a 62 7c 09 d3 2c System BIOS: VMW71.00V.16722896.B64.2008100651 2020-08-10
```

Did you completely log out of the environment?
