### ISSUE TITLE
cim_operations error

### ISSUE THREAD

**Issue by tcapacci** [Napsty/check_esxi_hardware#60]
I am using Ubuntu, the srip[t used to work great but since a few months I am getting:

nag@nag01:~# /usr/local/nagios/libexec/check_esxi_hardware.py -H 10.129.175.102 -U root -P Passw0rd!
Traceback (most recent call last):
  File "/usr/local/nagios/libexec/check_esxi_hardware.py", line 781, in <module>
    except pywbem.cim_operations.CIMError as args:
AttributeError: 'module' object has no attribute 'cim_operations'

**Comment by Napsty** [comment]
Please run the plugin in verbose mode. 
What has changed since it stopped working? OS Upgrade? ESXi upgrade? Python change?

**Comment by tcapacci** [comment]
I did a dist-upgrade on my Ubuntu server

The verbose mode is:

/usr/local/nagios/libexec/check_esxi_hardware.py -H 10.129.175.102 -U root -P Dell123! -v
20211111 15:56:39 LCD Status: True
20211111 15:56:39 Chassis Intrusion Status: True
20211111 15:56:39 Connection to https://10.129.175.102
20211111 15:56:39 Found pywbem version 1.1.2
20211111 15:56:39 Check classe OMC_SMASHFirmwareIdentity
Traceback (most recent call last):
  File "/usr/local/nagios/libexec/check_esxi_hardware.py", line 781, in <module>
    except pywbem.cim_operations.CIMError as args:
AttributeError: 'module' object has no attribute 'cim_operations'

**Comment by Napsty** [comment]
@tcapacci thx for the quick response. Can you upgrade pywbem to 1.2.0? See my recent successful tests on https://www.claudiokuenzler.com/blog/1110/check_esxi_hardware-esxi-compatibility-matrix-list

**Comment by tcapacci** [comment]
Thanks to you!

Just did but same message

root@remcorpnag01:~# /usr/local/nagios/libexec/check_esxi_hardware.py -H 10.129.175.102 -U root -P Dell123! -v
20211111 16:02:51 LCD Status: True
20211111 16:02:51 Chassis Intrusion Status: True
20211111 16:02:51 Connection to https://10.129.175.102
20211111 16:02:51 Found pywbem version 1.2.0
20211111 16:02:51 Check classe OMC_SMASHFirmwareIdentity
Traceback (most recent call last):
  File "/usr/local/nagios/libexec/check_esxi_hardware.py", line 781, in <module>
    except pywbem.cim_operations.CIMError as args:
AttributeError: 'module' object has no attribute 'cim_operations'

**Comment by Napsty** [comment]
OK, weird. What happens if you use `-V dell` as an argument?

**Comment by tcapacci** [comment]
same message

**Comment by Napsty** [comment]
Running out of ideas here... Can you try to remove and (re-) install the OMSA bundle? Certain versions are known to cause problems (see FAQ). You may also have to try the custom DELL ESXi ISO to see if it works there. 
Another workaround is to disable (comment) the OMC_SMASHFirmwareIdentity class in the plugin (around line 304): https://github.com/Napsty/check_esxi_hardware/blob/master/check_esxi_hardware.py#L304. This way you can rule out a general problem of the CIM server.

**Comment by ls440** [comment]
any update
