### ISSUE TITLE
Compatiblity with patched pywbem

### ISSUE THREAD

**Issue by Napsty** [Napsty/check_esxi_hardware#7]
In the previous months, Fedora (tbv), RedHat, Centos and Suse have applied patches to their pywbem packages. One of them is to verify the certificate. As most ESXi systems don't have a "real" ssl certificate, the following error is then shown when the plugin is run:

    Unknown CIM Error: (0, 'SSL error: certificate verify failed') 

This error can be solved by adding "no_verification" to the wbem connection string:

    wbemclient = pywbem.WBEMConnection(hosturl, (user,password), NS, no_verification=True)

But this won't work for earlier releases and for the upstream version of pywbem. 

According to the pywbem-dev mailing list, a new version (0.8.0) is being prepared for release. When this release hits the web, the plugin will be adapted to run with "no_verification parameter" when the pywbem package is newer than 0.7.0. Until then .. sleep.

**Comment by Napsty** [comment]
Commit 3f97ca6485a0130a92300cb5dd6104de0c5474be should resolve this.

**Comment by Napsty** [comment]
Successfully tested commit 3f97ca6485a0130a92300cb5dd6104de0c5474be on:

- openSUSE 13.2 with python 2.7.8 and pywbem 0.8.0-dev.r728 (from upstream source)
- Ubuntu 14.04 LTS (trusty) with python 2.7.6 and pywbem 0.7.0-4ubuntu1~14.04.1 (from Ubuntu repo)

**Comment by Napsty** [comment]
Just commited 6c8a4bfd63b934bb24bb21d7900afb64075135d3 
Successfully tested commit 6c8a4bfd63b934bb24bb21d7900afb64075135d3 on:

- openSUSE 13.2 with python 2.7.8 and pywbem 0.8.0-dev.r728 (from upstream source)
- Ubuntu 14.04 LTS (trusty) with python 2.7.6 and pywbem 0.7.0-4ubuntu1~14.04.1 (from Ubuntu repo)
- Ubuntu 12.04 LTS (precise) with python 2.7.3 and pywbem 0.7.0-4 (from Ubuntu repo)

**Comment by Napsty** [comment]
Patched code as version 20150626 officially released. Closing this issue.

**Comment by fasilcv86** [comment]
Hi

I'm using vSphere 6.7 and Nagios core 4.4. 

Installed VMware sdk 6.7 and check the connection, it's working. 

Which python plug I can use it. I have tested same in this repository but no luck.
