### ISSUE TITLE
Error when using Esxi 5.5U1 IBM Custom Image

### ISSUE THREAD

**Issue by jonasalexandersson** [Napsty/check_esxi_hardware#9]
/usr/lib/nagios/plugins/check_esxi_hardware.py -H x.x.x.x -U root -P secret_pass -v -V ibm

20141104 18:40:38 Connection to https://x.x.x.x
20141104 18:40:38 Check classe OMC_SMASHFirmwareIdentity
20141104 18:40:38   Element Name = System BIOS
20141104 18:40:38     VersionString = -[D7E142AUS-1.71]-
20141104 18:40:38 Check classe CIM_Chassis
20141104 18:40:38   Element Name = Chassis
20141104 18:40:38     Manufacturer = IBM
20141104 18:40:38     SerialNumber = xxxxx
20141104 18:40:38     Model = IBM System x3550 M4: -[7914J3G]-
20141104 18:40:38     Element Op Status = 0
20141104 18:40:38 Check classe CIM_Card
Traceback (most recent call last):
  File "/usr/lib/nagios/plugins/check_esxi_hardware1.py", line 625, in <module>
    verboseoutput("  Element Name = "+elementName)
TypeError: cannot concatenate 'str' and 'NoneType' objects

Version of plugin: = '20140319'
Regular Esxi 5.5U1 works fine.

**Comment by Napsty** [comment]
Possibly fixed with commit 60b03332f990a14c929123de8c8026cc92fd454b
Please try it.

**Comment by jonasalexandersson** [comment]
Yes!

Working as expected now!
Thanks a million=)

Kind Regards / Jonas




2015-01-15 15:17 GMT+01:00 Claudio Kuenzler <notifications@github.com>:

**Comment by Napsty** [comment]
Thank you for the confirmation. The fix will be published today with release version 20150119.
